amobit/urls.py
from django.conf.urls import include, url
from django.contrib import admin 

urlpatterns = [    
url(r'^admin/', admin.site.urls),
url(r'', include('oursite.urls'))
]

oursite/urls.py
# Use include() to add paths from the catalog application 
from django.urls import path
from django.conf import settings
from django.conf.urls import include, url
from .import views


app_name='oursite'
urlpatterns = [    
    path('index/',views.index,name='index'),
    path('index/contact-us', views.contact ,name='contact'),
    path('index/register',views.register, name='register'),
    path('index/about-us',views.about_us, name='about_us'),
    path('index/services',views.services, name='services'),
    path('index/products',views.products,name='products'),
]

oursite/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class Contact_us(models.Model):
    firstname = models.CharField(max_length=20)
    lastname = models.CharField(max_length=20)
    email = models.CharField(max_length=30)
    subject = models.CharField( max_length=50)
    message = models.CharField(max_length=500)
    def __str__(self):
        return (self.firstname,self.lastname,self.email,self.subject,self.message)


class SubscribeModel(models.Model):
    sys_id = models.AutoField(primary_key=True, null=False, blank=True)
    email = models.EmailField(null=False, blank=True, max_length=200, unique=True)
    status = models.CharField(max_length=64, null=False, blank=True)
    created_date = models.DateTimeField(null=False, blank=True)
    updated_date = models.DateTimeField(null=False, blank=True)

    class Meta:
        app_label = "appname"
        db_table = "appname_subscribe"

    def __str__(self):
        return self.email

oursite/forms.py
from django import forms
from .models import Contact_us

class contactForm(forms.ModelForm):
    firstname =forms.CharField(label='firstname')
    lastname =forms.CharField(label='lastname')
    email =forms.CharField(label='email')
    subject =forms.CharField(label='subject')
    message =forms.CharField(label='message')
    class Meta:
        model = Contact_us
        fields = ('firstname','lastname', 'email', 'subject', 'message')

oursite/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib import messages
from .models import Contact_us
from .forms import contactForm
from django.core.mail import send_mail
from django.core.mail import EmailMessage
from django.conf import settings
from django.template import RequestContext


# Create your views here.

def index(request):
    return render(request,'oursite/index.html',{})

def contact(request):
    if request.method == 'POST':
        contact_form = contactForm(data=request.POST)
        # print(contact_form.errors)
        if contact_form.is_valid():
            firstname = contact_form.cleaned_data['firstname']
            lastname = contact_form.cleaned_data['lastname']
            email = contact_form.cleaned_data['email']
            subject= contact_form.cleaned_data['subject']
            message= contact_form.cleaned_data['message']
            contact_form.save()
              
            first_name = request.POST.get('firstname')
            last_name= request.POST.get('lastname')
            subject_retrieve= request.POST.get('subject')
            message_retrieve= request.POST.get('message')
            message_retrieve= message_retrieve+ '\t'+'from :'+'\t'+first_name +'\t'+ last_name+ '\n'+'with email:'+'\n'+email 
            email_from = settings.EMAIL_HOST_USER
            recipient_list = ['amobittechnologiez@gmail.com']
            xxx = send_mail(subject,message_retrieve,email_from,recipient_list,fail_silently=False)
            messages.success(request,"Your message has been submitted")
            
            return render(request, 'oursite/contact-us.html', {})
        else:
            messages.error(request,"Data to be submitted is invalid")
            return render(request,'oursite/contact-us.html',{})

    else:
        return render(request,'oursite/contact-us.html', {})

def register(request):
    return render(request,'oursite/register.html',{})

def about_us(request):
    return render(request,'oursite/about-us.html',{})  

def services(request):
    return render(request,'oursite/services.html',{})    

def products(request):
    return render(request,'oursite/wex.html',{})    

oursite/templates/oursite/about-us.html
{% extends 'oursite/base.html'%}
{% load static%}
{% block body %}
<div class="about-us">
<div class="container-fluid mb-5 mt-5">
    <div class="row">
        <div class="col-md-3">

        </div>
        <div class="col-md-6">
            <div>
                <h2 class="font-weight-bolder text-center">About us</h2>
                <p class="">Amobit technologies is an ICT company in Uganda with Talented ICT specialists with a lot of skills aiming to solve community problems using new technology.
                    Organizations face challenges on their digital evolution journey. New technologies offer new possibilities for where and how to conduct business.Customers expect more as competitors raise the bar on what constitutes good service. Amobit technologies services deliver solutions that meet the challenges.We’re a network of innovators. 
                    We devise bold solutions to the most client challenges. It’s our ability to explore new technologies to design best-fit solutions</p>
            </div>
            

        </div>
    
        <div class="col-md-3">


        </div>
    </div>
    <div class="row">
        <div class="col-md-3">

        </div>
        <div class="col-md-6">
            <h2 class="font-weight-bold text-body">Mission</h2> 
            <p>To develop and sell reliable and sustainable Digital Solutions.</p>           
            <h2 class="font-weight-bold text-body">Vision</h2> 
            <p>Avail a Robust interconnected software ecosystem for our community.</p> 
        </div>

    </div>


    </div>

    
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">

        </div>
        <div class="col-md-6 core_values" style="font-family: 'Times New Roman', Times, serif;">
            <div class="">
                <h2 class="font-weight-bolder text-center">Our Core Values</h2>
                <h4 class="font-weight-bold">Customer Centricity</h4>
                <p class="text-justify">Our products, services and all our operation focus most on satisfying and tackling customer needs.
                     We always develop software that solve pressing matters of the people in our community who we take as our first hand customers.</p>
                <h4 class="font-weight-bold">Integrity</h4>
                <p>We understand and take seriously the matter of privacy and personal data protection therefore, we in the first place take
                     it as our priority to safe guard all the personal information from our customers through our products.</p>
                <h4 class="font-weight-bold">Innovation</h4>
                <p>Without creativity in solving problems then we are doing contrary to our mission 
                    therefore we must always consider innovative solutions to our problems more so in the ever rapid changing technology world.</p>
                <h4 class="font-weight-bold">Boldness</h4>
                <p>We endeavor to take fast steps towards identified opportunities because its only in this way we can make a positive impact in our community and ensure our continuous survival.</p>
                <h4 class="font-weight-bold">Team Work</h4>
                <p>We value the philosophy of working together to achieve a common goal. In this we believe we can deliver quality products and services faster.</p>
                <h4 class="font-weight-bold">Responsibility</h4>
                <p>AMOBIT TECHNOLOGIES will always work and act in responsible ways not to harm societies for this is our valuable market of today and tomorrow. Harming them is harming ourselves.</p>
            </div>

        </div>
        <div class="col-md-3">

        </div>

    </div>

</div>
<div id="services">
    <div class="box py-4">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <h2 class="mb-0 font-weight-bolder">Our Team</h2>
            </div>
          </div>
        </div>
      </div>
    
  </div>
<div class="container">
    
    <div class="row">
        <div class="col-md-4 text-center">
            <img class="rounded-circle wow bounce" src="{% static 'images/ceo.jpeg' %}" height="150" width="150" alt="Client 1 logo" class="img-responsive">

            
            <p class=""> <strong>Tayebwa Ian</strong> <br><span><strong>Role:</strong></span>CEO/marketing manager<br>
                <span>follow</span><i class="fa fa-twitter"></i><a href="https://www.twitter.com/IanTayebwa1"><span class="text-primary">@iantaye</span></a></p> <br>
        </div>
        <div class="col-md-4 text-center">
            <img class="rounded-circle wow bounce" src="{% static 'images/samuelitwaru.jpeg' %}" height="150" width="150" alt="Client 1 logo" class="img-responsive">

              
            <p class=""> <strong>Itwaru Samuel</strong> <br><span><strong>Role:</strong></span>General Secretary<br>
                <a href="" class="text-primary">follow<i class="fa fa-twitter"></i><span>@samuelitwaru</span></a></p> 
        </div>
        <div class="col-md-4 text-center">
            <img class="rounded-circle wow bounce" src="{% static 'images/mutesi.jpeg' %}" height="150" width="150" alt="Client 1 logo" class="img-responsive">

              
            <p class="mt-2"> <strong>Wilbrod Mutesi</strong><br><span><strong>Role:</strong></span>Operational Manager<br>
                <span>follow</span><i class="fa fa-twitter"></i><a href="https://www.twitter.com/MutesiWilbrod"><span class="text-primary">@MutesiWilbrod</span></a></p>          
        </div>
    </div>
        <div class="row">
            <div class="col-md-4 text-center">
                <img class="rounded-circle wow bounce" src="{% static 'images/lawrence.jpeg' %}" height="150" width="150" alt="Client 1 logo" class="img-responsive">
                      <p class=""> <strong>Lawrence Ainembabazi</strong> <br><span><strong>Role:</strong>:</span>Research Manager<br>
                    <a href="" class="text-primary">follow<i class="fa fa-twitter"></i><span>@ainelaw</span></a></p>
              
            </div>
            <div class="col-md-4 text-center">
                <img class="rounded-circle wow bounce" src="{% static 'images/joshua.jpeg' %}" height="150" width="150" alt="Client 1 logo" class="img-responsive">

                  
                <p class=""> <strong>Joshua Aaron Byenkya</strong> <br><span><strong>Role:</strong></span>Developer<br>
                    <a href="" class="text-primary">follow<i class="fa fa-twitter"></i><span>@aaronbyenkya</span></a></p>    
            </div>
            <div class="col-md-4 text-center">
                <img class="rounded-circle wow bounce" src="{% static 'images/olet.jpeg' %}" height="150" width="150" alt="Client 1 logo" class="img-responsive">

                  
                <p class=""> <strong>Charles Olet</strong> <br><span><strong>Role:</strong></span>Developer<br>
                    <a href="" class="text-primary">follow<i class="fa fa-twitter"></i><span>@Charlesolet</span></a></p>    
            </div>
    
        </div>
    </div>
    </div>


{% endblock %}

oursite/templates/oursite/contact-us.html
{% extends 'oursite/base.html' %}
{% load static %}

{% block body%}
<div class="container-fluid mt-5">
    <div class="row ">
        <div class="col-md-6 col-sm-12">
          <h1 class="text-center">Where to find us</h1>
                <!-- <div id="map" class="embed-responsive-item" style="height: 100%;width: 100%;font-family: 'Times New Roman', Times, serif;"></div> -->
                <div id="map" class="z-depth-1-half map-container" style="height: 500px">
                <iframe  frameborder="0"
                  style="border:0" allowfullscreen></iframe>
              </div>
        </div>
        

        <div class="col-md-6 col-sm-12 contact_form">
          <div class="col-md-9 col-sm-9">
              <div id="contact" class="">
                <h1 class="text-center wow slideInLeft">Contact Us</h1>
                <p class="font-weight-light">
                  If you have any questions, we would love to help. We have our offices open from Monday to Friday 9am - 5.30pm (EAT)
                </p>
                <hr>
                
              
                <h2 class="text-center">Send us message</h2>
                <form class="box contactForm" method="POST" action="{% url 'oursite:contact'%}" name="">
                  {% csrf_token %}
                  <div class="row" >
                    <div class="col-md-6">
                      <div class="form-group">
                        <label for="firstname">Firstname</label>
                        <input id="firstname" maxlength="20" required type="text" class="form-control" name="firstname">
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label for="lastname">Lastname</label>
                        <input id="lastname" maxlength="20" required type="text" class="form-control" name="lastname">
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label for="email">Email</label>
                        <input id="email" maxlength="30" required type="text" class="form-control" name="email">
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label for="subject">Subject</label>
                        <input id="subject" maxlength="50" required type="text" class="form-control" name="subject">
                      </div>
                    </div>
                    <div class="col-md-12">
                      <div class="form-group">
                        <label for="message">Message</label>
                        <textarea id="message" maxlength="500" required class="form-control" name="message"></textarea>
                      </div>
                    </div>
                    <div class="col-md-12 text-center">
                      <button type="submit" class="btn btn-outline-primary" value="submit"><i class="fa fa-envelope-o"></i> Send message</button>
                    </div>
                  </div>
                  <!-- /.row-->
                </form>

                <div class="row mt-5">
                  <div class="col-md-4">
                    <h3><i class="fa fa-map-marker"></i>Address</h3>
                    <p>Arua-Nebbi-Kampala road<br>Euata Guest House<br>Pl0t 16<br>Arua<br>Uganda</p>
                  </div>
                  <!-- /.col-sm-4-->
                  <div class="col-md-4">
                    <h3><i class="fa fa-phone"></i> Call center</h3>
                    <p>+256 785857000<br> Tayebwa Ian<br>CEO</p>
                    <p>+256 781902516<br>Itwaru Samuel<br>General Secretary</p>
                  </div>
                  <!-- /.col-sm-4-->
                  <div class="col-md-4">
                    <h3><i class="fa fa-envelope"></i> E-mail</h3>
                    <br>
                    
                    <a href="mailto:">amobittechnologiez@gmail.com</a>
                    
                  </div>
                  <!-- /.col-sm-4-->
                </div>
                <!-- /.row-->
              </div>
            </div>
        </div>
          
          
    </div>
</div>

{% endblock %}

oursite/templates/oursite/index.html
{% extends 'oursite/base.html'%}
{% load static %}
    

        
{% block body %}

  <div class="all mt-5">
    <!--slide show-->
    <div id="content">
        <div class="container">
            <div class="row">
              <div class="col-md-12">
                <div id="carouselExampleIndicators" class="carousel slide corousel-fade" data-ride="carousel">
                  <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>

                  </ol>
                  <div class="carousel-inner">
                    <div class="carousel-item active">
                      <img src="{% static 'images/canva2.jpeg'%}" class="d-block h-40 w-100 img-fluid" alt="office">
                      <div class="carousel-caption d-none d-md-block">
                      
                      </div>
                    </div>
                    <div class="carousel-item">
                      <img src="{% static 'images/canva6.jpeg'%}" class="d-block w-100 img-fluid " alt="ojukua2">
                    </div>
                    <div class="carousel-item">
                      <img src="{% static 'images/inkoop.jpeg'%}" class="d-block w-100 img-fluid" alt="inkoop">
              
                    </div>
                    <div class="carousel-item">
                      <img src="{% static 'images/canva5.jpeg'%}" class="d-block w-100 img-fluid" alt="inkoop">
              
                    </div>
                  </div>
                  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  </a>
                  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  </a>
                </div>
              </div>
            </div>
        </div>
    </div>
    <!--slider end-->
    <!--who are we-->

    <div id="who-we-are">
      <div class="container mt-3">
        <div class="color_design row mb-4">
          <div class="col-md-4">
            <div class="box clickable d-flex flex-column justify-content-center mb-0 h-100 w-100">
              <div class="icon"><i class="fa fa-thumbs-up"></i></div>
              <h3 class="font-weight-bold" >Who are we??</h3>
              <p class="mb-0">Talented ICT specialists with a lot of skills aiming to solve community problems using new technology</p>
            </div>
          </div>
          <div class="col-md-4">
            <div class="box clickable d-flex flex-column justify-content-center mb-0 h-100">
              <div class="icon"><i class="fa fa-heart"></i></div>
              <h3 class="font-weight-bold">Let's fast foward your business</h3>
              <p class="mb-0">We’re a network of innovators. We devise bold solutions to the most client challenges. It’s our ability to explore new technologies to design best-fit solutions</p>
      
            </div>
          </div>
          <div class="col-md-4">
            <div class="box clickable d-flex flex-column justify-content-center mb-0 h-100">
              <div class="icon"><i class="fa fa-thumbs-up"></i></div>
              <h3 class="font-weight-bold">Technology partner for your marketing agency</h3>
              <p class="mb-3">You are good at marketing strategy and creative things, and we are good at technology – let’s build amazing websites and mobile apps together and inspire each other’s growth.</p>
              
            </div>
          </div>
        </div>
      </div>
      <!-- /.container-->
    </div>

    <!---our services-->
    <div id="services">
      <div class="box py-4">
          <div class="container">
            <div class="row">
              <div class="col-md-12">
                <h2 class="mb-0 text-weight-bolder animated bounce" style="font-weight:bold;">Our Services</h2>
              </div>
            </div>
          </div>
        </div>
    </div>

    <div class="services block block-bg-gradient block-border-bottom">
      <div class="container">
        <div class="row">
          <div class="col-md-4 text-center">
            <span class="fa-stack fa-5x">
              <i class="fa fa-circle fa-stack-2x" style="color:#047CFC"></i>
              <i class="fa fa-address-card-o fa-stack-1x fa-inverse"></i> 
            </span>

            <h4 class="font-weight-bolder mt-3">
                Software Development 
            </h4>
            <p>We develop, deploy and maintain Industrial standard software like mobile applications, management systems, desktop systems and standard websites among many others.  
            </p>
          </div>
          <div class="col-md-4 text-center">
            <span class="fa-stack fa-5x">
              <i class="fa fa-circle fa-stack-2x" style="color: #047CFC;"></i>
              <i class="fa fa-laptop fa-stack-1x fa-inverse"></i> </span>
            <h4 class="font-weight-bolder mt-3">
              IT equipment Supplies
              </h4>
            <p>Basing on our outstanding experience using different kinds of IT equipment we are the best choice to contact when in need of reliable IT equipment supplies that best fit your
                specifications which include but not limited to all categories of computers, printers, scanners, connector cables and cameras </p>
          </div>
          <div class="col-md-4 text-center">
            <span class="fa-stack fa-5x">
              <i class="fa fa-circle fa-stack-2x" style="color:#047CFC"></i>
              <i class="fa fa-window-restore fa-stack-1x fa-inverse"></i>
              </span>
            <h4 class="font-weight-bolder mt-3">
              Software Installation and Configuration
              </h4>
            <p>We have and provide all software that you need to get your computers working, that is genuine operating systems and all their licensed application programs. </p>
          </div>
        </div>
      </div>
    </div>
    <!--another line-->

    <div class="services block block-bg-gradient block-border-bottom">
      <div class="container">
        <div class="row">
          <div class="col-md-4 text-center">
            <span class="fa-stack fa-5x">
              <i class="fa fa-circle fa-stack-2x" style="color:#047CFC"></i>
              <i class="fa fa-edit fa-stack-1x fa-inverse"></i>
             </span>

            <h4 class="font-weight-bolder">
              Graphics Design
              </h4>
            <p>This involves designing banners, logos, animations, wedding cards, business cards, identity Cards to mention but a few.
            </p>
          </div>
          <div class="col-md-4 text-center">
            <span class="fa-stack fa-5x">
              <i class="fa fa-circle fa-stack-2x" style="color:#047CFC"></i>
              <i class="fa fa-file-text-o fa-stack-1x fa-inverse"></i> </span>
            <h4 class="font-weight-bolder">
              Data Entry
              </h4>
            <p>We have skilled workforce that can help you in data collection and the challenging part of data entry in analytical systems. </p>
          </div>
          <div class="col-md-4 text-center">
            <span class="fa-stack fa-5x">
              <i class="fa fa-circle fa-stack-2x" style="color:#047CFC"></i>
              <i class="fa fa-cogs fa-stack-1x fa-inverse"></i> </span>
            <h4 class="font-weight-bolder">
                Other Services
              </h4>
            <p>Among these major services we provide other minor but essential services like consultancy services,web-hosting type setting, online registration and computer training. </p>
          </div>
        </div>
      </div>
    </div>

    <!-------services end-->
    <div id="our_clients">
      <div class="box py-4">
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-12 col-sm-12">
                <h2 class="mb-0 font-weight-bolder animated fadeInRight">Our partners</h2>
              </div>
            </div>
          </div>
        </div>
    </div>

    <div class="container mt-5 mb-5">
      <div class="">
        <div class="row">
          <!--Client logos should be within a 120px wide by 60px height image canvas-->
          <div class="col-xs-6 col-md-2 col-sm-12">
            <!-- <a href="" title="Client 1">
                <img class="" src="{% static 'images/oasis.png' %}" height="150" width="150" alt="Client 1 logo" class="img-responsive">
              </a> -->
          </div>
          <div class="col-xs-6 col-md-2 col-sm-12">
            <!-- <a href="" title="Client 2">
                <img class="rounded-circle" src="{% static 'images/oasis.png' %}" width="150" height="100" alt="Client 2 logo" class="img-responsive">
              </a> -->
          </div>
          <div class="justify-center col-xs-6 col-md-2 col-sm-12">
            <a href="" title="Client 3">
                <img class=""src="{% static 'images/oasis.jpeg' %}" alt="Client 3 logo" class="img-responsive" height="150px" width="150px">
              </a>
          </div>
          <div class="col-xs-6 col-md-2 col-sm-12">
              <a href="" title="Client 4">
                  <img class="" src="{% static 'images/ojukua_logo.jpeg' %}" alt="Client 4 logo" class="img-responsive" height="150px" width="150px">
              </a>
          </div>
          <div class="col-xs-6 col-md-2 col-sm-12">
            <!-- <a href="" title="Client 4">
              <img class="" src="{% static 'images/muni.png' %}" alt="Client 4 logo" class="img-responsive" height="150px" width="150px">
          </a> -->
          </div>
          <div class="col-xs-6 col-md-2 col-sm-12">
            <!-- <a href="" title="Client 6">
                <img  class="rounded-circle" src="{% static 'images/client2.jpeg' %}" alt="Client 6 logo" class="img-responsive">
            </a> -->
          </div>
        </div>
      </div>
    </div>
  </div>
  
{% endblock %}

oursite/templates/oursite/products.html
{% extends 'oursite/base.html'%}
{% load static %}
{% block body %}
<div class="container mt-5">
    <h1 class="text-center text-body text-primary">Our products</h1>
    <div class="row">
        <div class="col-md-4">
            <div class="media-body">
                <img src="{% static 'images/photo.png'%}" class="mr-3 align-self-start" alt="..." height="100px" width="300px">
                <div class="media-body">
                  <h5 class="mt-2 text-body text-center" style="font-weight: bolder;">Wex Information System</h5>
                  <p>This is a one stop stand sales management system for any
                    restaurant, bar and hotel business category.<a class="pl-2 text-primary" href="">read more</a></p>
                  
                </div>
            </div>

        </div>
        <div class="col-md-4">
            <div class="media">
                <img src="{% static ''%}" class="align-self-start mr-3" alt="...">
                <div class="media-body">
                  <h5 class="mt-2">Wex Information system</h5>
                  <p>This is a one stop stand sales management system for any
                    restaurant,bar and hotel business category.</p>
                  
                </div>
            </div>

        </div>
        <div class="col-md-4">
            <div class="media">
                <img src="{% static ''%}" class="align-self-start mr-3" alt="...">
                <div class="media-body">
                  <h5 class="mt-2">Wex Information system</h5>
                  <p>This is a one stop stand sales management system for any
                    restaurant, bar and hotel business category.</p>
                  
                </div>
            </div>

        </div>
        

    </div>    
    <div class="row">
        <div class="col-md-4">

        </div>
        <div class="col-md-4">

        </div>
        <div class="col-md-4">

        </div>

    </div>
</div>
{% endblock%}

oursite/templates/oursite/wex.html
{% extends 'oursite/base.html'%}
{% load static %}
{% block body %}
<div class="wex mt-1">
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">

        </div>
        <div class="col-md-6">
            <h2>Wex Information System</h2>

            <p class="" style="font-size: large;">Wex is a one stop stand sales management system for any
                restaurant, bar and hotel business category.</p>


        </div>
        <div class="col-md-3">

        </div>

    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">

        </div>
        <div class="col-md-6">
            <h3 class="mt-5 text-body">Benefits to your business</h3>

            <ul class="" style="font-size: large;">
                <li>Greater efficiency and less waste</li>
                <li>Better and consistent control of major business processes</li>
                <li>Better understanding of customer needs (Knowing what
                    sales most)</li>
                <li>Regulation of successful working practices</li>

                <li>Improved risk management (knowing the profitability of your business over a period)</li>
                <li>Increased customer satisfaction</li>
                <li>Improved participation of employees (Clear results of
                    employee performance acquired from the system)</li>
                <li>Greater consistency in the quality of products and services
                    (through setting standards in the system)</li>
                <li>Differentiation of your business from its competitors</li>
                <li>Reduction of costly errors (through automation of business
                    processes)</li>
                <li>Managing growth more effectively</li>
                <li>An embedded culture of quality</li>
                <li>Increased profits</li>

            </ul>
        </div>
        <div class="col-md-3">

        </div>

    </div>
</div>
<!--- corousel images-->
<section id="services" class="mb-5">
    <div class="container">

      <div class="">
        <h2 class="">Screenshots</h2>
      </div>

      <div class="row">
        <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up">
          <div class="">
              <img src="{% static 'images/oasis4.jpeg'%}" height="200px" width="300px">
          </div>
        </div>
        <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up">
            <div class="">
                <img src="{% static 'images/oasis1.jpeg'%}" class="img-fluid" height="200px" width="300px">
            </div>
          </div>
          <div class="col-lg-4 col-md-6 icon-box" data-aos="fade-up">
            <div class="">
                <img src="{% static 'images/oasis2.jpeg'%}" class="img-fluid" height="200px" width="300px">
            </div>
          </div>
      </div>

    </div>
</section>
 

</div>
{% endblock %}